### ISSUE TITLE
Asus X205TA (ELAN0100:00 04F3:0401)

### ISSUE THREAD

**Issue by maxogden** [zhaostu/chromium-os-touchpad#6]
I have Chromium OS booting on the X205TA, but the trackpad only shows up as a mouse (so no two finger scroll etc), and manually installing the Elantech conf from this repo didn't have any effect.

The trackpad seems to be quite new, as there are no google results for the product ID from `/proc/bus/input/devices`:

```
I: Bus=0018 Vendor=04f3 Product=0401 Version=0100
N: Name="ELAN0100:00 04F3:0401"
P: Phys=
S: Sysfs=/devices/platform/80860F41:03/i2c-11/i2c-ELAN0100:00/0018:04F3:0401.0002/input/input9
U: Uniq=
H: Handlers=mouse0 event9
B: PROP=0
B: EV=17
B: KEY=30000 0 0 0 0
B: REL=103
B: MSC=10
```

I also recently found this Ubuntu ticket mentioning a similar trackpad that cited a possible fix, but I'm not sure if that is applicable here: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1439111

Mostly I'm just posting here so if anyone else fixes it this will show up in their google search and they can leave their fix here or send a PR :)

**Comment by paulcbetts** [comment]
If you're lucky, you might be able to just patch the existing driver and add the PID to the list:

https://lkml.org/lkml/2015/3/31/929

Patch `hid-core` to include `0x0401` like this guy did for `0x0400`

**Comment by zhaostu** [comment]
As @paulcbetts mentioned I think it should be a missing driver. I'll leave this ticket open and see if anyone come up with anything.

**Comment by maxogden** [comment]
theres an official driver for this now https://lkml.org/lkml/2015/8/24/647

**Comment by zhaostu** [comment]
Great! Thanks!
