### ISSUE TITLE
Request for more drivers

### ISSUE THREAD

**Issue by bastian94** [zhaostu/chromium-os-touchpad#7]
It would be wounder ful if you can add more driver support to your tool like this for example https://chromium.googlesource.com/chromiumos/platform/xorg-conf/+/master

**Comment by zhaostu** [comment]
Hmm, I wonder whether those configurations works for non-chromebook laptops.

Looks like what is in there is configured for all Chromebooks, you may want to test whether any one of them works with your non-chromebook touchpad.

**Comment by zhaostu** [comment]
@bastian94 you can see here for the list of chromebooks. http://www.chromium.org/chromium-os/developer-information-for-chrome-os-devices/

**Comment by bastian94** [comment]
I am trying to install the touch drive in chromium using your tool on a chromebook that is not longer can run the normal chrome os. That's why i asked you to add the config files for chromebooks

**Comment by zhaostu** [comment]
@bastian94 what did you do to not able to run official Chrome OS? Maybe restoring the OS is a better solution?

**Comment by bastian94** [comment]
I have flashed another bios on chromebook and when i am restoring it to chrome os it's some problems with some files so i don't get any updates from google that's why i am using chromium

**Comment by zhaostu** [comment]
@bastian94 Got ya.
This project is really not for that purpose. I don't have a chromebook (thus not able to test any of the configurations whether they work), and I don't know a way to detect the model of chromebook.

That said, one thing you could do, is to download the appropriate `50-touchpad-cmt-***.conf` file from official repo to `/etc/X11/xorg.conf.d/` on the chrome os, and override the default one there. Hope you can get it working.

**Comment by bastian94** [comment]
You can say that this feture is untested.

**Comment by zhaostu** [comment]
@bastian94 If you are interested, you can submit a pull request. I don't have a Chromebook and I don't have a way to find the model of the Chromebook automatically to install the configuration.
