### ISSUE TITLE
https://github.com/zhaostu/chromium-os-touchpad

### ISSUE THREAD

**Issue by XxPoNaGeXx** [zhaostu/chromium-os-touchpad#8]
No known touch pad found, exiting

**Comment by zhaostu** [comment]
hmm. what kind of laptop do you have?

This script is written a long time ago and touchpads are changing a lot I imagine.

**Comment by XxPoNaGeXx** [comment]
It's an ASUS X540S, could it be something to do with my BIOS boot settings as I had to change them to get the OS to start. Maybe my touchpad isn't being loaded

**Comment by zhaostu** [comment]
What are the files in /proc/bus/input/devices in your Linux file system?

**Comment by XxPoNaGeXx** [comment]
chronos@localhost / $ cd /proc/bus/input/devices
bash: cd: /proc/bus/input/devices: Not a directory

I was on Windows 10 originally

**Comment by XxPoNaGeXx** [comment]
Could it have something to do with my BIOS boot settings?

**Comment by zhaostu** [comment]
Your Windows 10 and Chromium OS does not share the file system.

I think you don't have access to the directory if you are not root user.

So try "sudu su" and then look what's in the directory

**Comment by XxPoNaGeXx** [comment]
bash: sudu: command not found
localhost / # ^C 

I am the root user, only account on the OS

**Comment by zhaostu** [comment]
I had a typo.

You were `chronos` user when you posted the previous comment.

Now, as root, can you go to that folder?

**Comment by XxPoNaGeXx** [comment]
bash: cd: /proc/bus/input/devices: Not a directory
localhost / #

**Comment by zhaostu** [comment]
Or find something that looks like a touchpad.

**Comment by XxPoNaGeXx** [comment]
localhost / # /proc/bus/input/devices
bash: /proc/bus/input/devices: Permission denied

Huh,  am the only account on here..

**Comment by XxPoNaGeXx** [comment]
I'd really like to use my touchpad, I'd love it if you could help me out!

**Comment by zhaostu** [comment]
do "cat /proc/bus/input/devices"

**Comment by zhaostu** [comment]
I meant, find something in that file that looks like a touchpad and paste it here.

**Comment by XxPoNaGeXx** [comment]
localhost / # cat /proc/bus/input/devices
I: Bus=0019 Vendor=0000 Product=0005 Version=0000
N: Name="Lid Switch"
P: Phys=PNP0C0D/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0D:00/input/input0
U: Uniq=
H: Handlers=event0 
B: PROP=0
B: EV=21
B: SW=1

I: Bus=0019 Vendor=0000 Product=0003 Version=0000
N: Name="Sleep Button"
P: Phys=PNP0C0E/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0E:00/input/input1
U: Uniq=
H: Handlers=kbd event1 
B: PROP=0
B: EV=3
B: KEY=4000 0 0

I: Bus=0019 Vendor=0000 Product=0001 Version=0000
N: Name="Power Button"
P: Phys=LNXPWRBN/button/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXPWRBN:00/input/input2
U: Uniq=
H: Handlers=kbd event2 
B: PROP=0
B: EV=3
B: KEY=10000000000000 0

I: Bus=0019 Vendor=0000 Product=0006 Version=0000
N: Name="Video Bus"
P: Phys=LNXVIDEO/video/input0
S: Sysfs=/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/LNXVIDEO:00/input/input3
U: Uniq=
H: Handlers=kbd event3 
B: PROP=0
B: EV=3
B: KEY=3e000b00000000 0 0 0

I: Bus=0011 Vendor=0001 Product=0001 Version=ab41
N: Name="AT Translated Set 2 keyboard"
P: Phys=isa0060/serio0/input0
S: Sysfs=/devices/platform/i8042/serio0/input/input4
U: Uniq=
H: Handlers=sysrq kbd leds event4 
B: PROP=0
B: EV=120013
B: KEY=702000000 3803078f800d001 feffffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=7

I: Bus=0003 Vendor=1ea7 Product=0011 Version=0110
N: Name="USB Mouse"
P: Phys=usb-0000:00:14.0-1/input0
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.0/0003:1EA7:0011.0001/input/input5
U: Uniq=
H: Handlers=event5 
B: PROP=0
B: EV=17
B: KEY=ff0000 0 0 0 0
B: REL=143
B: MSC=10

I: Bus=0003 Vendor=1ea7 Product=0011 Version=0110
N: Name="USB Mouse"
P: Phys=usb-0000:00:14.0-1/input1
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-1/1-1:1.1/0003:1EA7:0011.0002/input/input6
U: Uniq=
H: Handlers=kbd event6 
B: PROP=0
B: EV=1f
B: KEY=3f0003007f 0 0 483ffff17aff32d bf54444600000000 1 130f938b17c000 677bfad9415fed 9ed68000004400 10000002
B: REL=40
B: ABS=100000000
B: MSC=10

I: Bus=0010 Vendor=001f Product=0001 Version=0100
N: Name="PC Speaker"
P: Phys=isa0061/input0
S: Sysfs=/devices/platform/pcspkr/input/input7
U: Uniq=
H: Handlers=kbd event7 
B: PROP=0
B: EV=40001
B: SND=6

I: Bus=0019 Vendor=0000 Product=0000 Version=0000
N: Name="Asus WMI hotkeys"
P: Phys=asus-nb-wmi/input0
S: Sysfs=/devices/platform/asus-nb-wmi/input/input8
U: Uniq=
H: Handlers=rfkill kbd event8 
B: PROP=0
B: EV=100013
B: KEY=c0000 0 800000000000 0 0 a1606f00900000 200027800501000 e000000000000 0
B: MSC=10

I: Bus=0003 Vendor=0bda Product=57de Version=0014
N: Name="USB2.0 VGA UVC WebCam"
P: Phys=usb-0000:00:14.0-4/button
S: Sysfs=/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.0/input/input10
U: Uniq=
H: Handlers=kbd event9 
B: PROP=0
B: EV=3
B: KEY=100000 0 0 0

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel PCH Headphone"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input9
U: Uniq=
H: Handlers=event10 
B: PROP=0
B: EV=21
B: SW=4

I: Bus=0000 Vendor=0000 Product=0000 Version=0000
N: Name="HDA Intel PCH HDMI/DP,pcm=3"
P: Phys=ALSA
S: Sysfs=/devices/pci0000:00/0000:00:1b.0/sound/card0/input11
U: Uniq=
H: Handlers=event11 
B: PROP=0
B: EV=21
B: SW=140

**Comment by zhaostu** [comment]
I don't think the Linux kernel detected the touchpad. There are two "USB Mouse" detected, but they look too similar that they seem to both be your external USB mouse.

At this point, I don't really have any idea how to make it work even if it is my laptop. I would try to copy those conf files included in this repo into the `/etc/X11/xorg.conf.d/??-touchpad-cmt.conf` one by one and see if any worked. If not, you are out of luck :(

**Comment by XxPoNaGeXx** [comment]
How do I do that?

**Comment by zhaostu** [comment]
There are three config files here: https://github.com/zhaostu/chromium-os-touchpad, named `<type>.xorg.conf`. Replace `/etc/X11/xorg.conf.d/<a two digit number>-touchpad-cmt.conf` with either of the three, reboot and see if it works.

On how to replace the file, you just have to learn a little bit Linux bash commands.

**Comment by XxPoNaGeXx** [comment]
HUh? What should I type. SOrry I don't know how to use shell at all

**Comment by zhaostu** [comment]
You should get a sense here: https://github.com/zhaostu/chromium-os-touchpad/blob/master/config-touchpad.sh

From line 21, and replace the variables with the right URL.

**Comment by XxPoNaGeXx** [comment]
I've been reading about these: https://www.reddit.com/r/chrubuntu/comments/1rsxkd/list_of_fixes_for_xubuntu_1310_on_the_acer_c720/cf82pk4/

 https://launchpad.net/~hugegreenbug/+archive/ubuntu/cmt

https://github.com/hugegreenbug/xf86-input-cmt

I am willing to try it if you can help me install it?

**Comment by zhaostu** [comment]
Those are two different things.

The things you linked are to port the CMT driver to Linux, but I assume you are trying to install Chromium OS on a regular laptop, which *already*  have the CMT driver and doesn't work.

**Comment by zhaostu** [comment]
This project is to fallback to a traditional driver.

**Comment by XxPoNaGeXx** [comment]
YEH I installed it on a windows laptop. Everything else other than the touchpad is working, is there any other option I can take to get the driver to work

**Comment by zhaostu** [comment]
Wait for Chromium OS updates? Sometimes that fixes the issue. See #6.

**Comment by XxPoNaGeXx** [comment]
So how do I install the driver then? https://lkml.org/lkml/2015/8/24/647

**Comment by zhaostu** [comment]
Get the latest Chromium OS

**Comment by zhaostu** [comment]
The drivers are in the Linux kernel and could not be "installed".

**Comment by XxPoNaGeXx** [comment]
I am on the latest though?

**Comment by XxPoNaGeXx** [comment]
Also, you may be able to help me with this. When I plug my headphones in the audio plays through both the headphones and speakers

**Comment by zhaostu** [comment]
Sorry, I have no idea how to help you on that.

**Comment by XxPoNaGeXx** [comment]
Alrighty
