### ISSUE TITLE
Script error /etc/X11/xorg.conf.d/40-touchpad-cmt.conf: No such file or directory

### ISSUE THREAD

**Issue by yelo3** [zhaostu/chromium-os-touchpad#9]
hello, I'm using CloudReady OS v 57.2
The changelog says that there has been a transition from X11 to Freon graphics stack

this is the command output
localhost etc # wget -qO- http://goo.gl/1VWycc | sh
ALPS touchpad detected.
Mounting the rootfs as read-write...
Creating backup for /etc/X11/xorg.conf.d/40-touchpad-cmt.conf...
cp: cannot stat ‘/etc/X11/xorg.conf.d/40-touchpad-cmt.conf’: No such file or directory

**Comment by james-balazs** [comment]
**I'm getting the same problem** but it's a Synaptics touchpad, which the script detects instead of the ALPS one above.
ChromeOS 54.0.2815.0 (64-bit)

**Comment by zhaostu** [comment]
Hi, thanks for using this script, but this script is no longer supported.

Your best bet is to look at the original solution this project is trying to automate:
http://arnoldthebat.co.uk/wordpress/2013/01/08/how-to-get-the-touch-pad-working-in-chromium-os/

and try to figure it out manually.

Good luck!

**Comment by zhaostu** [comment]
@yelo3 this project works with X11 configuration files, and will definitely not work with Freon.

You should ask CloudReady OS support on why your touchpad does not work.

**Comment by elninoisback** [comment]
The .conf file is now in /etc/gesture folder.
